# ============================================================
# File Name   : 20260528_0001_init_models.py
# Description:
#   创建初始语义数据模型表结构。
#
# Responsibilities:
#   - 创建数据集、指标、维度和会话相关表。
#   - 提供初始表结构的回滚逻辑。
#
# Author      : yangkai
# Created On  : 2026-06-05
# ============================================================

"""init models

Revision ID: 20260528_0001
Revises:
Create Date: 2026-05-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260528_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
        sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
        sa.Column('agent_id', sa.Integer(), nullable=True, comment='代理 ID'),
        sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
        sa.Column('thread_id', sa.String(length=64), nullable=True, comment='LangGraph 线程 ID'),
        sa.Column('user_id', sa.Integer(), nullable=True, comment='用户 ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='用户会话表',
    )
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)

    op.create_table('datasource',
        sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='数据源名称'),
        sa.Column('db_type', sa.String(length=20), nullable=False, comment='数据库类型（mysql/postgres等）'),
        sa.Column('host', sa.String(length=255), nullable=False, comment='主机地址'),
        sa.Column('port', sa.Integer(), nullable=False, comment='端口号'),
        sa.Column('database_name', sa.String(length=100), nullable=False, comment='数据库名'),
        sa.Column('username', sa.String(length=100), nullable=False, comment='连接用户名'),
        sa.Column('password_enc', sa.Text(), nullable=False, comment='加密存储的连接密码'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='数据源连接配置表',
    )
    op.create_index(op.f('ix_datasource_id'), 'datasource', ['id'], unique=False)

    op.create_table('semantic_dataset',
        sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='数据集名称'),
        sa.Column('datasource_id', sa.Integer(), nullable=False, comment='所属数据源 ID'),
        sa.Column('tables_json', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='关联物理表信息 JSON'),
        sa.Column('description', sa.Text(), nullable=True, comment='数据集描述'),
        sa.Column('status', sa.String(length=20), nullable=True, comment='数据集状态'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='语义数据集表',
    )
    op.create_index(op.f('ix_semantic_dataset_id'), 'semantic_dataset', ['id'], unique=False)

    op.create_table('message',
        sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
        sa.Column('conversation_id', sa.Integer(), nullable=False, comment='所属会话 ID'),
        sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色（user/assistant）'),
        sa.Column('content', sa.Text(), nullable=False, comment='消息文本内容'),
        sa.Column('sql_list', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='生成的 SQL 列表'),
        sa.Column('report_html', sa.Text(), nullable=True, comment='报告 HTML 内容'),
        sa.Column('token_usage', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='token 用量统计'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='会话消息表',
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)

    op.create_table('semantic_dimension',
        sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
        sa.Column('dataset_id', sa.Integer(), nullable=False, comment='所属数据集 ID'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='维度英文名'),
        sa.Column('display_name', sa.String(length=100), nullable=False, comment='维度显示名称'),
        sa.Column('column_name', sa.String(length=100), nullable=False, comment='对应物理列名'),
        sa.Column('enum_values', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='枚举值列表'),
        sa.Column('synonyms', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='同义词列表'),
        sa.ForeignKeyConstraint(['dataset_id'], ['semantic_dataset.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='语义维度表',
    )
    op.create_index(op.f('ix_semantic_dimension_id'), 'semantic_dimension', ['id'], unique=False)

    op.create_table('semantic_metric',
        sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
        sa.Column('dataset_id', sa.Integer(), nullable=False, comment='所属数据集 ID'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='指标英文名'),
        sa.Column('display_name', sa.String(length=100), nullable=False, comment='指标显示名称'),
        sa.Column('expr', sa.Text(), nullable=False, comment='聚合计算表达式'),
        sa.Column('filter_sql', sa.Text(), nullable=True, comment='过滤条件 SQL'),
        sa.Column('synonyms', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='同义词列表'),
        sa.Column('description', sa.Text(), nullable=True, comment='指标描述'),
        sa.ForeignKeyConstraint(['dataset_id'], ['semantic_dataset.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='语义指标表',
    )
    op.create_index(op.f('ix_semantic_metric_id'), 'semantic_metric', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_metric_id'), table_name='semantic_metric')
    op.drop_table('semantic_metric')
    op.drop_index(op.f('ix_semantic_dimension_id'), table_name='semantic_dimension')
    op.drop_table('semantic_dimension')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_semantic_dataset_id'), table_name='semantic_dataset')
    op.drop_table('semantic_dataset')
    op.drop_index(op.f('ix_datasource_id'), table_name='datasource')
    op.drop_table('datasource')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
